//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `ServeurIce.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __ServeurIce_h__
#define __ServeurIce_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/ValueF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Comparable.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/GCObject.h>
#include <Ice/Value.h>
#include <Ice/Incoming.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/Optional.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace server
{

class ServeurIce;
class ServeurIcePrx;

}

namespace server
{

struct Musique
{
    int id;
    ::std::string name;
    ::std::string artist;

    /**
     * Obtains a tuple containing all of the exception's data members.
     * @return The data members in a tuple.
     */

    std::tuple<const int&, const ::std::string&, const ::std::string&> ice_tuple() const
    {
        return std::tie(id, name, artist);
    }
};

using bdd = ::std::vector<Musique>;

using Ice::operator<;
using Ice::operator<=;
using Ice::operator>;
using Ice::operator>=;
using Ice::operator==;
using Ice::operator!=;

}

namespace server
{

class ServeurIce : public virtual ::Ice::Object
{
public:

    using ProxyType = ServeurIcePrx;

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(::std::string id, const ::Ice::Current& current) const override;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector<::std::string> ice_ids(const ::Ice::Current& current) const override;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual ::std::string ice_id(const ::Ice::Current& current) const override;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual bool ajouterMusique(::std::string name, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_ajouterMusique(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void jouerMusique(int id, const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_jouerMusique(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void display(const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_display(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual bdd getBdd(const ::Ice::Current& current) = 0;
    /// \cond INTERNAL
    bool _iceD_getBdd(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&) override;
    /// \endcond
};

}

namespace server
{

class ServeurIcePrx : public virtual ::Ice::Proxy<ServeurIcePrx, ::Ice::ObjectPrx>
{
public:

    bool ajouterMusique(const ::std::string& name, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<bool>(true, this, &ServeurIcePrx::_iceI_ajouterMusique, name, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto ajouterMusiqueAsync(const ::std::string& name, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<bool>>().get_future())
    {
        return _makePromiseOutgoing<bool, P>(false, this, &ServeurIcePrx::_iceI_ajouterMusique, name, context);
    }

    ::std::function<void()>
    ajouterMusiqueAsync(const ::std::string& name,
                        ::std::function<void(bool)> response,
                        ::std::function<void(::std::exception_ptr)> ex = nullptr,
                        ::std::function<void(bool)> sent = nullptr,
                        const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<bool>(response, ex, sent, this, &server::ServeurIcePrx::_iceI_ajouterMusique, name, context);
    }

    /// \cond INTERNAL
    void _iceI_ajouterMusique(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<bool>>&, const ::std::string&, const ::Ice::Context&);
    /// \endcond

    void jouerMusique(int id, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &ServeurIcePrx::_iceI_jouerMusique, id, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto jouerMusiqueAsync(int id, const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &ServeurIcePrx::_iceI_jouerMusique, id, context);
    }

    ::std::function<void()>
    jouerMusiqueAsync(int id,
                      ::std::function<void()> response,
                      ::std::function<void(::std::exception_ptr)> ex = nullptr,
                      ::std::function<void(bool)> sent = nullptr,
                      const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &server::ServeurIcePrx::_iceI_jouerMusique, id, context);
    }

    /// \cond INTERNAL
    void _iceI_jouerMusique(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, int, const ::Ice::Context&);
    /// \endcond

    void display(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        _makePromiseOutgoing<void>(true, this, &ServeurIcePrx::_iceI_display, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto displayAsync(const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<void>>().get_future())
    {
        return _makePromiseOutgoing<void, P>(false, this, &ServeurIcePrx::_iceI_display, context);
    }

    ::std::function<void()>
    displayAsync(::std::function<void()> response,
                 ::std::function<void(::std::exception_ptr)> ex = nullptr,
                 ::std::function<void(bool)> sent = nullptr,
                 const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<void>(response, ex, sent, this, &server::ServeurIcePrx::_iceI_display, context);
    }

    /// \cond INTERNAL
    void _iceI_display(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>&, const ::Ice::Context&);
    /// \endcond

    bdd getBdd(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makePromiseOutgoing<bdd>(true, this, &ServeurIcePrx::_iceI_getBdd, context).get();
    }

    template<template<typename> class P = ::std::promise>
    auto getBddAsync(const ::Ice::Context& context = ::Ice::noExplicitContext)
        -> decltype(::std::declval<P<bdd>>().get_future())
    {
        return _makePromiseOutgoing<bdd, P>(false, this, &ServeurIcePrx::_iceI_getBdd, context);
    }

    ::std::function<void()>
    getBddAsync(::std::function<void(bdd)> response,
                ::std::function<void(::std::exception_ptr)> ex = nullptr,
                ::std::function<void(bool)> sent = nullptr,
                const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _makeLamdaOutgoing<bdd>(response, ex, sent, this, &server::ServeurIcePrx::_iceI_getBdd, context);
    }

    /// \cond INTERNAL
    void _iceI_getBdd(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<bdd>>&, const ::Ice::Context&);
    /// \endcond

    /**
     * Obtains the Slice type ID of this interface.
     * @return The fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:

    /// \cond INTERNAL
    ServeurIcePrx() = default;
    friend ::std::shared_ptr<ServeurIcePrx> IceInternal::createProxy<ServeurIcePrx>();

    virtual ::std::shared_ptr<::Ice::ObjectPrx> _newInstance() const override;
    /// \endcond
};

}

/// \cond STREAM
namespace Ice
{

template<>
struct StreamableTraits<::server::Musique>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 6;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamReader<::server::Musique, S>
{
    static void read(S* istr, ::server::Musique& v)
    {
        istr->readAll(v.id, v.name, v.artist);
    }
};

}
/// \endcond

/// \cond INTERNAL
namespace server
{

using ServeurIcePtr = ::std::shared_ptr<ServeurIce>;
using ServeurIcePrxPtr = ::std::shared_ptr<ServeurIcePrx>;

}
/// \endcond

#else // C++98 mapping

namespace IceProxy
{

namespace server
{

class ServeurIce;
/// \cond INTERNAL
void _readProxy(::Ice::InputStream*, ::IceInternal::ProxyHandle< ServeurIce>&);
::IceProxy::Ice::Object* upCast(ServeurIce*);
/// \endcond

}

}

namespace server
{

class ServeurIce;
/// \cond INTERNAL
::Ice::Object* upCast(ServeurIce*);
/// \endcond
typedef ::IceInternal::Handle< ServeurIce> ServeurIcePtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::server::ServeurIce> ServeurIcePrx;
typedef ServeurIcePrx ServeurIcePrxPtr;
/// \cond INTERNAL
void _icePatchObjectPtr(ServeurIcePtr&, const ::Ice::ObjectPtr&);
/// \endcond

}

namespace server
{

struct Musique
{
    ::Ice::Int id;
    ::std::string name;
    ::std::string artist;

    bool operator==(const Musique& rhs_) const
    {
        if(this == &rhs_)
        {
            return true;
        }
        if(id != rhs_.id)
        {
            return false;
        }
        if(name != rhs_.name)
        {
            return false;
        }
        if(artist != rhs_.artist)
        {
            return false;
        }
        return true;
    }

    bool operator<(const Musique& rhs_) const
    {
        if(this == &rhs_)
        {
            return false;
        }
        if(id < rhs_.id)
        {
            return true;
        }
        else if(rhs_.id < id)
        {
            return false;
        }
        if(name < rhs_.name)
        {
            return true;
        }
        else if(rhs_.name < name)
        {
            return false;
        }
        if(artist < rhs_.artist)
        {
            return true;
        }
        else if(rhs_.artist < artist)
        {
            return false;
        }
        return false;
    }

    bool operator!=(const Musique& rhs_) const
    {
        return !operator==(rhs_);
    }
    bool operator<=(const Musique& rhs_) const
    {
        return operator<(rhs_) || operator==(rhs_);
    }
    bool operator>(const Musique& rhs_) const
    {
        return !operator<(rhs_) && !operator==(rhs_);
    }
    bool operator>=(const Musique& rhs_) const
    {
        return !operator<(rhs_);
    }
};

typedef ::std::vector<Musique> bdd;

}

namespace server
{

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::server::ServeurIce::begin_ajouterMusique.
 * Create a wrapper instance by calling ::server::newCallback_ServeurIce_ajouterMusique.
 */
class Callback_ServeurIce_ajouterMusique_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_ServeurIce_ajouterMusique_Base> Callback_ServeurIce_ajouterMusiquePtr;

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::server::ServeurIce::begin_jouerMusique.
 * Create a wrapper instance by calling ::server::newCallback_ServeurIce_jouerMusique.
 */
class Callback_ServeurIce_jouerMusique_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_ServeurIce_jouerMusique_Base> Callback_ServeurIce_jouerMusiquePtr;

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::server::ServeurIce::begin_display.
 * Create a wrapper instance by calling ::server::newCallback_ServeurIce_display.
 */
class Callback_ServeurIce_display_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_ServeurIce_display_Base> Callback_ServeurIce_displayPtr;

/**
 * Base class for asynchronous callback wrapper classes used for calls to
 * IceProxy::server::ServeurIce::begin_getBdd.
 * Create a wrapper instance by calling ::server::newCallback_ServeurIce_getBdd.
 */
class Callback_ServeurIce_getBdd_Base : public virtual ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_ServeurIce_getBdd_Base> Callback_ServeurIce_getBddPtr;

}

namespace IceProxy
{

namespace server
{

class ServeurIce : public virtual ::Ice::Proxy<ServeurIce, ::IceProxy::Ice::Object>
{
public:

    bool ajouterMusique(const ::std::string& name, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_ajouterMusique(_iceI_begin_ajouterMusique(name, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_ajouterMusique(const ::std::string& name, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_ajouterMusique(name, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_ajouterMusique(const ::std::string& name, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_ajouterMusique(name, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_ajouterMusique(const ::std::string& name, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_ajouterMusique(name, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_ajouterMusique(const ::std::string& name, const ::server::Callback_ServeurIce_ajouterMusiquePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_ajouterMusique(name, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_ajouterMusique(const ::std::string& name, const ::Ice::Context& context, const ::server::Callback_ServeurIce_ajouterMusiquePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_ajouterMusique(name, context, cb, cookie);
    }

    bool end_ajouterMusique(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_ajouterMusique(const ::std::string&, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void jouerMusique(::Ice::Int id, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_jouerMusique(_iceI_begin_jouerMusique(id, context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_jouerMusique(::Ice::Int id, const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_jouerMusique(id, context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_jouerMusique(::Ice::Int id, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_jouerMusique(id, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_jouerMusique(::Ice::Int id, const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_jouerMusique(id, context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_jouerMusique(::Ice::Int id, const ::server::Callback_ServeurIce_jouerMusiquePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_jouerMusique(id, ::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_jouerMusique(::Ice::Int id, const ::Ice::Context& context, const ::server::Callback_ServeurIce_jouerMusiquePtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_jouerMusique(id, context, cb, cookie);
    }

    void end_jouerMusique(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_jouerMusique(::Ice::Int, const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    void display(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        end_display(_iceI_begin_display(context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_display(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_display(context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_display(const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_display(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_display(const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_display(context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_display(const ::server::Callback_ServeurIce_displayPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_display(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_display(const ::Ice::Context& context, const ::server::Callback_ServeurIce_displayPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_display(context, cb, cookie);
    }

    void end_display(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_display(const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    ::server::bdd getBdd(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return end_getBdd(_iceI_begin_getBdd(context, ::IceInternal::dummyCallback, 0, true));
    }

    ::Ice::AsyncResultPtr begin_getBdd(const ::Ice::Context& context = ::Ice::noExplicitContext)
    {
        return _iceI_begin_getBdd(context, ::IceInternal::dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getBdd(const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getBdd(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getBdd(const ::Ice::Context& context, const ::Ice::CallbackPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getBdd(context, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getBdd(const ::server::Callback_ServeurIce_getBddPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getBdd(::Ice::noExplicitContext, cb, cookie);
    }

    ::Ice::AsyncResultPtr begin_getBdd(const ::Ice::Context& context, const ::server::Callback_ServeurIce_getBddPtr& cb, const ::Ice::LocalObjectPtr& cookie = 0)
    {
        return _iceI_begin_getBdd(context, cb, cookie);
    }

    ::server::bdd end_getBdd(const ::Ice::AsyncResultPtr& result);

private:

    ::Ice::AsyncResultPtr _iceI_begin_getBdd(const ::Ice::Context&, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& cookie = 0, bool sync = false);

public:

    /**
     * Obtains the Slice type ID corresponding to this interface.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

protected:
    /// \cond INTERNAL

    virtual ::IceProxy::Ice::Object* _newInstance() const;
    /// \endcond
};

}

}

namespace server
{

class ServeurIce : public virtual ::Ice::Object
{
public:

    typedef ServeurIcePrx ProxyType;
    typedef ServeurIcePtr PointerType;

    virtual ~ServeurIce();

    /**
     * Determines whether this object supports an interface with the given Slice type ID.
     * @param id The fully-scoped Slice type ID.
     * @param current The Current object for the invocation.
     * @return True if this object supports the interface, false, otherwise.
     */
    virtual bool ice_isA(const ::std::string& id, const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a list of the Slice type IDs representing the interfaces supported by this object.
     * @param current The Current object for the invocation.
     * @return A list of fully-scoped type IDs.
     */
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains a Slice type ID representing the most-derived interface supported by this object.
     * @param current The Current object for the invocation.
     * @return A fully-scoped type ID.
     */
    virtual const ::std::string& ice_id(const ::Ice::Current& current = ::Ice::emptyCurrent) const;

    /**
     * Obtains the Slice type ID corresponding to this class.
     * @return A fully-scoped type ID.
     */
    static const ::std::string& ice_staticId();

    virtual bool ajouterMusique(const ::std::string& name, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_ajouterMusique(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void jouerMusique(::Ice::Int id, const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_jouerMusique(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual void display(const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_display(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    virtual bdd getBdd(const ::Ice::Current& current = ::Ice::emptyCurrent) = 0;
    /// \cond INTERNAL
    bool _iceD_getBdd(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

    /// \cond INTERNAL
    virtual bool _iceDispatch(::IceInternal::Incoming&, const ::Ice::Current&);
    /// \endcond

protected:

    /// \cond STREAM
    virtual void _iceWriteImpl(::Ice::OutputStream*) const;
    virtual void _iceReadImpl(::Ice::InputStream*);
    /// \endcond
};

/// \cond INTERNAL
inline bool operator==(const ServeurIce& lhs, const ServeurIce& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) == static_cast<const ::Ice::Object&>(rhs);
}

inline bool operator<(const ServeurIce& lhs, const ServeurIce& rhs)
{
    return static_cast<const ::Ice::Object&>(lhs) < static_cast<const ::Ice::Object&>(rhs);
}
/// \endcond

}

/// \cond STREAM
namespace Ice
{

template<>
struct StreamableTraits< ::server::Musique>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 6;
    static const bool fixedLength = false;
};

template<typename S>
struct StreamWriter< ::server::Musique, S>
{
    static void write(S* ostr, const ::server::Musique& v)
    {
        ostr->write(v.id);
        ostr->write(v.name);
        ostr->write(v.artist);
    }
};

template<typename S>
struct StreamReader< ::server::Musique, S>
{
    static void read(S* istr, ::server::Musique& v)
    {
        istr->read(v.id);
        istr->read(v.name);
        istr->read(v.artist);
    }
};

}
/// \endcond

namespace server
{

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::server::ServeurIce::begin_ajouterMusique.
 * Create a wrapper instance by calling ::server::newCallback_ServeurIce_ajouterMusique.
 */
template<class T>
class CallbackNC_ServeurIce_ajouterMusique : public Callback_ServeurIce_ajouterMusique_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(bool);

    CallbackNC_ServeurIce_ajouterMusique(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ServeurIcePrx proxy = ServeurIcePrx::uncheckedCast(result->getProxy());
        bool ret;
        try
        {
            ret = proxy->end_ajouterMusique(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::server::ServeurIce::begin_ajouterMusique.
 */
template<class T> Callback_ServeurIce_ajouterMusiquePtr
newCallback_ServeurIce_ajouterMusique(const IceUtil::Handle<T>& instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ServeurIce_ajouterMusique<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::server::ServeurIce::begin_ajouterMusique.
 */
template<class T> Callback_ServeurIce_ajouterMusiquePtr
newCallback_ServeurIce_ajouterMusique(T* instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ServeurIce_ajouterMusique<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::server::ServeurIce::begin_ajouterMusique.
 * Create a wrapper instance by calling ::server::newCallback_ServeurIce_ajouterMusique.
 */
template<class T, typename CT>
class Callback_ServeurIce_ajouterMusique : public Callback_ServeurIce_ajouterMusique_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(bool, const CT&);

    Callback_ServeurIce_ajouterMusique(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ServeurIcePrx proxy = ServeurIcePrx::uncheckedCast(result->getProxy());
        bool ret;
        try
        {
            ret = proxy->end_ajouterMusique(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::server::ServeurIce::begin_ajouterMusique.
 */
template<class T, typename CT> Callback_ServeurIce_ajouterMusiquePtr
newCallback_ServeurIce_ajouterMusique(const IceUtil::Handle<T>& instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ServeurIce_ajouterMusique<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::server::ServeurIce::begin_ajouterMusique.
 */
template<class T, typename CT> Callback_ServeurIce_ajouterMusiquePtr
newCallback_ServeurIce_ajouterMusique(T* instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ServeurIce_ajouterMusique<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::server::ServeurIce::begin_jouerMusique.
 * Create a wrapper instance by calling ::server::newCallback_ServeurIce_jouerMusique.
 */
template<class T>
class CallbackNC_ServeurIce_jouerMusique : public Callback_ServeurIce_jouerMusique_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_ServeurIce_jouerMusique(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::server::ServeurIce::begin_jouerMusique.
 */
template<class T> Callback_ServeurIce_jouerMusiquePtr
newCallback_ServeurIce_jouerMusique(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ServeurIce_jouerMusique<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::server::ServeurIce::begin_jouerMusique.
 */
template<class T> Callback_ServeurIce_jouerMusiquePtr
newCallback_ServeurIce_jouerMusique(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ServeurIce_jouerMusique<T>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::server::ServeurIce::begin_jouerMusique.
 */
template<class T> Callback_ServeurIce_jouerMusiquePtr
newCallback_ServeurIce_jouerMusique(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ServeurIce_jouerMusique<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::server::ServeurIce::begin_jouerMusique.
 */
template<class T> Callback_ServeurIce_jouerMusiquePtr
newCallback_ServeurIce_jouerMusique(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ServeurIce_jouerMusique<T>(instance, 0, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::server::ServeurIce::begin_jouerMusique.
 * Create a wrapper instance by calling ::server::newCallback_ServeurIce_jouerMusique.
 */
template<class T, typename CT>
class Callback_ServeurIce_jouerMusique : public Callback_ServeurIce_jouerMusique_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_ServeurIce_jouerMusique(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::server::ServeurIce::begin_jouerMusique.
 */
template<class T, typename CT> Callback_ServeurIce_jouerMusiquePtr
newCallback_ServeurIce_jouerMusique(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ServeurIce_jouerMusique<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::server::ServeurIce::begin_jouerMusique.
 */
template<class T, typename CT> Callback_ServeurIce_jouerMusiquePtr
newCallback_ServeurIce_jouerMusique(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ServeurIce_jouerMusique<T, CT>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::server::ServeurIce::begin_jouerMusique.
 */
template<class T, typename CT> Callback_ServeurIce_jouerMusiquePtr
newCallback_ServeurIce_jouerMusique(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ServeurIce_jouerMusique<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::server::ServeurIce::begin_jouerMusique.
 */
template<class T, typename CT> Callback_ServeurIce_jouerMusiquePtr
newCallback_ServeurIce_jouerMusique(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ServeurIce_jouerMusique<T, CT>(instance, 0, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::server::ServeurIce::begin_display.
 * Create a wrapper instance by calling ::server::newCallback_ServeurIce_display.
 */
template<class T>
class CallbackNC_ServeurIce_display : public Callback_ServeurIce_display_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_ServeurIce_display(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::server::ServeurIce::begin_display.
 */
template<class T> Callback_ServeurIce_displayPtr
newCallback_ServeurIce_display(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ServeurIce_display<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::server::ServeurIce::begin_display.
 */
template<class T> Callback_ServeurIce_displayPtr
newCallback_ServeurIce_display(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ServeurIce_display<T>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::server::ServeurIce::begin_display.
 */
template<class T> Callback_ServeurIce_displayPtr
newCallback_ServeurIce_display(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ServeurIce_display<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::server::ServeurIce::begin_display.
 */
template<class T> Callback_ServeurIce_displayPtr
newCallback_ServeurIce_display(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ServeurIce_display<T>(instance, 0, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::server::ServeurIce::begin_display.
 * Create a wrapper instance by calling ::server::newCallback_ServeurIce_display.
 */
template<class T, typename CT>
class Callback_ServeurIce_display : public Callback_ServeurIce_display_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_ServeurIce_display(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::server::ServeurIce::begin_display.
 */
template<class T, typename CT> Callback_ServeurIce_displayPtr
newCallback_ServeurIce_display(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ServeurIce_display<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::server::ServeurIce::begin_display.
 */
template<class T, typename CT> Callback_ServeurIce_displayPtr
newCallback_ServeurIce_display(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ServeurIce_display<T, CT>(instance, 0, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::server::ServeurIce::begin_display.
 */
template<class T, typename CT> Callback_ServeurIce_displayPtr
newCallback_ServeurIce_display(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ServeurIce_display<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::server::ServeurIce::begin_display.
 */
template<class T, typename CT> Callback_ServeurIce_displayPtr
newCallback_ServeurIce_display(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ServeurIce_display<T, CT>(instance, 0, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class used for calls to
 * IceProxy::server::ServeurIce::begin_getBdd.
 * Create a wrapper instance by calling ::server::newCallback_ServeurIce_getBdd.
 */
template<class T>
class CallbackNC_ServeurIce_getBdd : public Callback_ServeurIce_getBdd_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const bdd&);

    CallbackNC_ServeurIce_getBdd(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ServeurIcePrx proxy = ServeurIcePrx::uncheckedCast(result->getProxy());
        bdd ret;
        try
        {
            ret = proxy->end_getBdd(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(ret);
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::server::ServeurIce::begin_getBdd.
 */
template<class T> Callback_ServeurIce_getBddPtr
newCallback_ServeurIce_getBdd(const IceUtil::Handle<T>& instance, void (T::*cb)(const bdd&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ServeurIce_getBdd<T>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::server::ServeurIce::begin_getBdd.
 */
template<class T> Callback_ServeurIce_getBddPtr
newCallback_ServeurIce_getBdd(T* instance, void (T::*cb)(const bdd&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ServeurIce_getBdd<T>(instance, cb, excb, sentcb);
}

/**
 * Type-safe asynchronous callback wrapper class with cookie support used for calls to
 * IceProxy::server::ServeurIce::begin_getBdd.
 * Create a wrapper instance by calling ::server::newCallback_ServeurIce_getBdd.
 */
template<class T, typename CT>
class Callback_ServeurIce_getBdd : public Callback_ServeurIce_getBdd_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const bdd&, const CT&);

    Callback_ServeurIce_getBdd(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    /// \cond INTERNAL
    virtual void completed(const ::Ice::AsyncResultPtr& result) const
    {
        ServeurIcePrx proxy = ServeurIcePrx::uncheckedCast(result->getProxy());
        bdd ret;
        try
        {
            ret = proxy->end_getBdd(result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(ret, CT::dynamicCast(result->getCookie()));
        }
    }
    /// \endcond

private:

    Response _response;
};

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::server::ServeurIce::begin_getBdd.
 */
template<class T, typename CT> Callback_ServeurIce_getBddPtr
newCallback_ServeurIce_getBdd(const IceUtil::Handle<T>& instance, void (T::*cb)(const bdd&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ServeurIce_getBdd<T, CT>(instance, cb, excb, sentcb);
}

/**
 * Creates a callback wrapper instance that delegates to your object.
 * Use this overload when your callback methods receive a cookie value.
 * @param instance The callback object.
 * @param cb The success method of the callback object.
 * @param excb The exception method of the callback object.
 * @param sentcb The sent method of the callback object.
 * @return An object that can be passed to an asynchronous invocation of IceProxy::server::ServeurIce::begin_getBdd.
 */
template<class T, typename CT> Callback_ServeurIce_getBddPtr
newCallback_ServeurIce_getBdd(T* instance, void (T::*cb)(const bdd&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ServeurIce_getBdd<T, CT>(instance, cb, excb, sentcb);
}

}

#endif

#include <IceUtil/PopDisableWarnings.h>
#endif
