//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `ServeurIce.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <ServeurIce.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_server_ServeurIce_ids[2] =
{
    "::Ice::Object",
    "::server::ServeurIce"
};
const ::std::string iceC_server_ServeurIce_ops[] =
{
    "ajouterMusique",
    "display",
    "getBdd",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "jouerMusique",
    "stopMusique"
};
const ::std::string iceC_server_ServeurIce_ajouterMusique_name = "ajouterMusique";
const ::std::string iceC_server_ServeurIce_jouerMusique_name = "jouerMusique";
const ::std::string iceC_server_ServeurIce_stopMusique_name = "stopMusique";
const ::std::string iceC_server_ServeurIce_display_name = "display";
const ::std::string iceC_server_ServeurIce_getBdd_name = "getBdd";

}

bool
server::ServeurIce::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_server_ServeurIce_ids, iceC_server_ServeurIce_ids + 2, s);
}

::std::vector<::std::string>
server::ServeurIce::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_server_ServeurIce_ids[0], &iceC_server_ServeurIce_ids[2]);
}

::std::string
server::ServeurIce::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
server::ServeurIce::ice_staticId()
{
    static const ::std::string typeId = "::server::ServeurIce";
    return typeId;
}

/// \cond INTERNAL
bool
server::ServeurIce::_iceD_ajouterMusique(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_name;
    istr->readAll(iceP_name);
    inS.endReadParams();
    bool ret = this->ajouterMusique(::std::move(iceP_name), current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::ServeurIce::_iceD_jouerMusique(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    int iceP_id;
    istr->readAll(iceP_id);
    inS.endReadParams();
    this->jouerMusique(iceP_id, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::ServeurIce::_iceD_stopMusique(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    bool ret = this->stopMusique(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::ServeurIce::_iceD_display(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    this->display(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::ServeurIce::_iceD_getBdd(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    bdd ret = this->getBdd(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::ServeurIce::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_server_ServeurIce_ops, iceC_server_ServeurIce_ops + 9, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_server_ServeurIce_ops)
    {
        case 0:
        {
            return _iceD_ajouterMusique(in, current);
        }
        case 1:
        {
            return _iceD_display(in, current);
        }
        case 2:
        {
            return _iceD_getBdd(in, current);
        }
        case 3:
        {
            return _iceD_ice_id(in, current);
        }
        case 4:
        {
            return _iceD_ice_ids(in, current);
        }
        case 5:
        {
            return _iceD_ice_isA(in, current);
        }
        case 6:
        {
            return _iceD_ice_ping(in, current);
        }
        case 7:
        {
            return _iceD_jouerMusique(in, current);
        }
        case 8:
        {
            return _iceD_stopMusique(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
server::ServeurIcePrx::_iceI_ajouterMusique(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<bool>>& outAsync, const ::std::string& iceP_name, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_server_ServeurIce_ajouterMusique_name);
    outAsync->invoke(iceC_server_ServeurIce_ajouterMusique_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_name);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
server::ServeurIcePrx::_iceI_jouerMusique(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, int iceP_id, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_server_ServeurIce_jouerMusique_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_id);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
server::ServeurIcePrx::_iceI_stopMusique(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<bool>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_server_ServeurIce_stopMusique_name);
    outAsync->invoke(iceC_server_ServeurIce_stopMusique_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
server::ServeurIcePrx::_iceI_display(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_server_ServeurIce_display_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
server::ServeurIcePrx::_iceI_getBdd(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<bdd>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_server_ServeurIce_getBdd_name);
    outAsync->invoke(iceC_server_ServeurIce_getBdd_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
server::ServeurIcePrx::_newInstance() const
{
    return ::IceInternal::createProxy<ServeurIcePrx>();
}
/// \endcond

const ::std::string&
server::ServeurIcePrx::ice_staticId()
{
    return ServeurIce::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_server_ServeurIce_ajouterMusique_name = "ajouterMusique";

const ::std::string iceC_server_ServeurIce_jouerMusique_name = "jouerMusique";

const ::std::string iceC_server_ServeurIce_stopMusique_name = "stopMusique";

const ::std::string iceC_server_ServeurIce_display_name = "display";

const ::std::string iceC_server_ServeurIce_getBdd_name = "getBdd";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::server::upCast(ServeurIce* p) { return p; }

void
::IceProxy::server::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< ServeurIce>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ServeurIce;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::server::ServeurIce::_iceI_begin_ajouterMusique(const ::std::string& iceP_name, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_server_ServeurIce_ajouterMusique_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_server_ServeurIce_ajouterMusique_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_server_ServeurIce_ajouterMusique_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_name);
        result->endWriteParams();
        result->invoke(iceC_server_ServeurIce_ajouterMusique_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

bool
IceProxy::server::ServeurIce::end_ajouterMusique(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_server_ServeurIce_ajouterMusique_name);
    bool ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::server::ServeurIce::_iceI_begin_jouerMusique(::Ice::Int iceP_id, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_server_ServeurIce_jouerMusique_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_server_ServeurIce_jouerMusique_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_id);
        result->endWriteParams();
        result->invoke(iceC_server_ServeurIce_jouerMusique_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::server::ServeurIce::end_jouerMusique(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_server_ServeurIce_jouerMusique_name);
}

::Ice::AsyncResultPtr
IceProxy::server::ServeurIce::_iceI_begin_stopMusique(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_server_ServeurIce_stopMusique_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_server_ServeurIce_stopMusique_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_server_ServeurIce_stopMusique_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_server_ServeurIce_stopMusique_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

bool
IceProxy::server::ServeurIce::end_stopMusique(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_server_ServeurIce_stopMusique_name);
    bool ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::server::ServeurIce::_iceI_begin_display(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_server_ServeurIce_display_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_server_ServeurIce_display_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_server_ServeurIce_display_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::server::ServeurIce::end_display(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_server_ServeurIce_display_name);
}

::Ice::AsyncResultPtr
IceProxy::server::ServeurIce::_iceI_begin_getBdd(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_server_ServeurIce_getBdd_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_server_ServeurIce_getBdd_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_server_ServeurIce_getBdd_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_server_ServeurIce_getBdd_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::server::bdd
IceProxy::server::ServeurIce::end_getBdd(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_server_ServeurIce_getBdd_name);
    ::server::bdd ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::server::ServeurIce::_newInstance() const
{
    return new ServeurIce;
}
/// \endcond

const ::std::string&
IceProxy::server::ServeurIce::ice_staticId()
{
    return ::server::ServeurIce::ice_staticId();
}

server::ServeurIce::~ServeurIce()
{
}

/// \cond INTERNAL
::Ice::Object* server::upCast(ServeurIce* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_server_ServeurIce_ids[2] =
{
    "::Ice::Object",
    "::server::ServeurIce"
};

}

bool
server::ServeurIce::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_server_ServeurIce_ids, iceC_server_ServeurIce_ids + 2, s);
}

::std::vector< ::std::string>
server::ServeurIce::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_server_ServeurIce_ids[0], &iceC_server_ServeurIce_ids[2]);
}

const ::std::string&
server::ServeurIce::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
server::ServeurIce::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::server::ServeurIce";
    return typeId;
#else
    return iceC_server_ServeurIce_ids[1];
#endif
}

/// \cond INTERNAL
bool
server::ServeurIce::_iceD_ajouterMusique(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_name;
    istr->read(iceP_name);
    inS.endReadParams();
    bool ret = this->ajouterMusique(iceP_name, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::ServeurIce::_iceD_jouerMusique(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Ice::Int iceP_id;
    istr->read(iceP_id);
    inS.endReadParams();
    this->jouerMusique(iceP_id, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::ServeurIce::_iceD_stopMusique(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    bool ret = this->stopMusique(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::ServeurIce::_iceD_display(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    this->display(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
server::ServeurIce::_iceD_getBdd(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    bdd ret = this->getBdd(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_server_ServeurIce_all[] =
{
    "ajouterMusique",
    "display",
    "getBdd",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "jouerMusique",
    "stopMusique"
};

}

/// \cond INTERNAL
bool
server::ServeurIce::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_server_ServeurIce_all, iceC_server_ServeurIce_all + 9, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_server_ServeurIce_all)
    {
        case 0:
        {
            return _iceD_ajouterMusique(in, current);
        }
        case 1:
        {
            return _iceD_display(in, current);
        }
        case 2:
        {
            return _iceD_getBdd(in, current);
        }
        case 3:
        {
            return _iceD_ice_id(in, current);
        }
        case 4:
        {
            return _iceD_ice_ids(in, current);
        }
        case 5:
        {
            return _iceD_ice_isA(in, current);
        }
        case 6:
        {
            return _iceD_ice_ping(in, current);
        }
        case 7:
        {
            return _iceD_jouerMusique(in, current);
        }
        case 8:
        {
            return _iceD_stopMusique(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
server::ServeurIce::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< ServeurIce, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
server::ServeurIce::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< ServeurIce, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
server::_icePatchObjectPtr(ServeurIcePtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ServeurIcePtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(ServeurIce::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
